[meta]
title="Getting Started with Fusion SQL"
description="""\
    Fusion SQL allows you to manage your SingleStoreDB Cloud
    resources such as workspace groups, workspaces, and
    Stage files all from SQL.
    """
icon="browser"
difficulty="beginner"
tags=["starter", "fusion", "python"]
lesson_areas=["Data Management", "Python SDK"]
destinations=["spaces"]
minimum_tier="standard"
