[meta]
title="Evaluating LLMs with Uptrain"
description="""\
Using Uptrain to evaluate LLMs built with SingleStore as the contextual store. This notebook uses OpenAI embedding models and Langchain as a development framework.
    """
tags=["openai", "llm", "vectordb", "langchain"]
icon="vector-circle"
destinations=["spaces"]
