[meta]
title="Learn how to Optimize Performance with TPCH 100"
description="""\
    This notebook will help you understand how you can take advantage of SingleStoreDB distributed capability using TPCH-100.
"""
icon="database"
difficulty="advanced"
tags=["advanced", "performance", "turning", "shardkey", "ingest", "tpch"]
lesson_areas=["Query Performance"]
destinations=["spaces"]
minimum_tier="standard"
