[meta]
author="singlestore"
title="Automatically warm up your disk after resuming workspace"
description="""\
    Runs through the queries to bring data residing in object storage onto disk for a specified database. \
    """
icon="database"
difficulty="advanced"
tags=["advanced", "automation", "tuning"]
lesson_areas=[]
destinations=["spaces"]
minimum_tier="standard"
