[meta]
title="Kafka Pipelines and Query Tuning"
description="""\
    Create a SingleStore pipeline to track the International Space Station and adjust queries & schema to optimize performance.
    """
tags=["beginner", "kafka", "pipeline","querytuning"]
icon="database"
destinations=["spaces"]
