[meta]
authors=["singlestore"]
title="Resume Evaluator"
description="""\
    Resume Evaluator using vectors stored in SingleStore to find sutiable resume for your job description. \
    """
icon="arrows-spin"
difficulty="intermediate"
tags=["starter", "vectordb", "genai", "openai"]
lesson_areas=["AI"]
destinations=["spaces"]
minimum_tier="free-shared"
