[meta]
title="IT Threat Detection, Part 3"
description="""
    Part 3 of Real-time threat Detection - Integrate with Kafka, run
    and visualize Threat Detection on incoming logs.
    This notebook requires adjustments to work out of the box."""
icon="browser"
tags=["advanced", "cybersecurity", "vectordb", "iot", "ai"]
destinations=["spaces"]
